config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get 'home/about', to: 'homes#about', as: 'about'
  devise_for :users

  resources :users, only:[:index,:show,:edit, :update]
  resources :books, only:[:index,:create,:show,:edit,:update,:destroy] do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create,:destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  validates :comment, presence: true
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates_uniqueness_of :book_id, scope: :user_id
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: { maximum: 50}

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width,height)
   unless profile_image.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
     profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    @book_comment = BookComment.find(params[:id])
    @book_comment.destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
    @newbook = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @newbook =Book.new(book_params)
    @newbook.user_id = current_user.id
    if @newbook.save
       redirect_to book_path(@newbook.id)
       flash[:notice] = "Book was successfully created."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end
  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @user = @book.user
  end
  def edit
    @book = Book.find(params[:id])
    redirect_to books_path unless current_user.id == @book.user_id
  end

  def update
     @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path(@book.id)
       flash[:notice] = "Book was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
   book = Book.find(params[:book_id])
   favorite = current_user.favorites.new(book_id: book.id)
   favorite.save
   redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @newbook = Book.new
    @users = User.all
    @user = current_user
  end
  def show
    @newbook = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless current_user.id == @user.id
  end

  def update
    @user = current_user
    if @user.update(user_params)
     redirect_to user_path(current_user.id)
     flash[:notice] = "You have updated user successfully."
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newbook.html.erb
<h1>New book</h1>

<%= form_with model: newbook, method: :post,local: true do |f| %>
 <h4>Title</h4>
 <%= f.text_field :title %>

 <h4>Opinion</h4>
 <%= f.text_area :body %>

 <%= f.submit 'Create Book'%>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj ffrom being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Opinion</h4>
<%= f.text_area :body %>

<%= f.submit 'Update Book' %>
<% end %>

<P><%= link_to 'Show', book_path(params[:id]) %></P>
<p><%= link_to 'Back', books_path %></p>

app/views/books/index.html.erb
<% if @newbook.errors.any? %>
  <%= @newbook.errors.count %> errors prohibited this obj ffrom being saved:
  <ul>
    <% @newbook.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<% if flash[:notice] %>
   <p id="notice">
    <%= flash[:notice] %>
   </p>
 <% end %>
<div class="container">
 <div class="row">
  <div class="col-md-3">
   <%= render 'users/userinfo', user: @user %>
   <%= render 'newbook', newbook: @newbook %>
  </div>
  <div class="col-md-8 offset-md-1">
   <h1>Books</h1>

   <table class="table table-striped">
    <thead>
     <tr>
     <th>Title</th>
     <th>Opinion</th>
     </tr>
     </thead>

     <tbody>
     <% @books.each do |book| %>
     <tr>
     <td><%= link_to user_path(book.user.id) do %>
        <%= image_tag book.user.get_profile_image(100,100) %>
       <% end %>
     </td>
     <td><%= link_to book.title, book_path(book.id) %></td>
     <td><%= book.body%></td>
     <td>コメント数：<%= book.book_comments.count %></td>
       <% if book.favorited_by?(current_user) %>
         <td>
           <%= link_to book_favorites_path(book), method: :delete do %>
             <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
           <% end %>
         </td>
        <% else %>
         <td>
           <%= link_to book_favorites_path(book), method: :post do %>
             <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
           <% end %>
         </td>
        <% end %>
    </tr>
     <% end %>
    </tbody>
   </div>
  </div>
 </div>
</table>

app/views/books/show.html.erb
<% if flash[:notice] %>
   <p id="notice">
    <%= flash[:notice] %>
   </p>
<% end %>
<div class="container">
 <div class="row">
  <div class="col-md-3">
   <%= render 'users/userinfo', user: @user %>
   <%= render 'newbook', newbook: @newbook %>
  </div>
  <div class="col-md-8 offset-md-1">
   <h1>Book detail</h1>
    <table class="table table-striped">
     <tbody>
      <tr>
       <td><%= link_to user_path(@book.user.id) do %>
        <%= image_tag @book.user.get_profile_image(100,100) %>
       <% end %>
       <%= link_to @book.user.name, user_path(@book.user.id) %>
       </td>
       <td><%= link_to @book.title, book_path(@book.id) %></td>
       <td><%= @book.body%></td>
       <td>コメント数：<%= @book.book_comments.count %></td>
       <% if @book.favorited_by?(current_user) %>
         <td>
           <%= link_to book_favorites_path(@book), method: :delete do %>
             <i class="fa-solid fa-heart"></i><%= @book.favorites.count %>
           <% end %>
         </td>
        <% else %>
         <td>
           <%= link_to book_favorites_path(@book), method: :post do %>
             <i class="fa-solid fa-heart"></i><%= @book.favorites.count %>
           <% end %>
         </td>
        <% end %>
        <% if @book.user.id == current_user.id %>
       <td><%= link_to 'Edit', edit_book_path(@book.id) %></td>
       <td><%= link_to 'Destroy', book_path(@book.id), method: :delete %></td>
       <% end %>
      </tr>
     </tbody>
    </table>
    <div>
      <% @book.book_comments.each do |book_comment| %>
        <p><%= image_tag book_comment.user.get_profile_image(100,100) %></p>
        <%= book_comment.user.name %>
        <%= book_comment.comment %>
        <% if book_comment.user == current_user %>
         <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
        <% end %>
      <% end %>
    </div>

    <div>
      <%= form_with model: [@book, @book_comment] do |f| %>
        <%= f.text_area :comment, rows: '5'%>
        <%= f.submit "送信" %>
      <% end %>
    </div>
  </div>
 </div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to <i class="fa-solid fas fa-book"></i>Bookers!</h1>

app/views/homes/top.html.erb
<% if flash[:notice] %>
   <p id="notice">
    <%= flash[:notice] %>
   </p>
<% end %>
<h1>welcome to <i class="fa-solid fas fa-book"></i>Bookers!!</h1>
<P>in <i class="fa-solid fas fa-book"></i>Bookers,</P>
<p>you can share and exchange your opinions, inpressions, and emotions</p>
<p>about various books!</p>

  <%= link_to "Log in", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container">
         <a class="navbar-brand" href="/">
           <span>Bookers</span>
         </a>
         <% if user_signed_in? %>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
               <%= link_to user_path(current_user.id) do %>
                <i class="fa-solid fas fa-home"></i>
                Home
               <% end %>
            </li>
            <li class="nav-item">
               <%= link_to users_path do %>
                <i class="fa-solid fas fa-users"></i>
                Users
               <% end %>
            </li>
            <li class="nav-item">
               <%= link_to books_path do %>
                <i class="fa-solid fas fa-book-open"></i>
                Books
               <% end %>
            </li>
            <li class="nav-item">
               <%= link_to  destroy_user_session_path, method: :delete do %>
                <i class="fa-solid fas fa-sign-out-alt"></i>
                logout
               <% end %>
            </li>
    </ul>
   </div>
   <% else %>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav mr-auto">
        <li class="nav-item">
               <%= link_to root_path do %>
                <i class="fa-solid fas fa-home"></i>
                Home
               <% end %>
            </li>
             <li class="nav-item">
               <%= link_to about_path do %>
                <i class="fa-solid fas fa-link"></i>
                About
               <% end %>
            </li>
             <li class="nav-item">
               <%= link_to new_user_registration_path do %>
                <i class="fa-solid fas fa-user-plus"></i>
                sign up
               <% end %>
            </li>
             <li class="nav-item">
               <%= link_to new_user_session_path do %>
                <i class="fa-solid fas fa-sign-in-alt"></i>
                login
               <% end %>
            </li>
        </ul>
       </div>
      <% end %>
           </div>



  </nav>
  </div>
</header>
<%= yield %>
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>
</body>
</html>

app/views/users/_userinfo.html.erb
<h2>User info</h2>
 <%= image_tag user.get_profile_image(100,100) %>
<table>
  <tbody class="table">
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>

  </tbody>
</table>
<div class="row">
<%= link_to edit_user_path(user.id), class:'btn btn-outline-secondary btn-block fas fa-user-cog' do %>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Users edit</h1>
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibitedthis obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @user do |f| %>
  <label>Name</label>
  <div><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"name"%></div>
  <label>Image</label>
  <div><%= f.file_field :profile_image, accept: "image/*" %></div>
  <label>Introduction</label>
  <div><%= f.text_field :introduction, autofocus: true %></div>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3">
  <%= render 'userinfo', user: @user %>
  <%= render 'books/newbook', newbook: @newbook %>
  </div>
  <div class="col-md-8 offset-md-1">
   <h1>Users</h1>
   <table class="table table-striped">
    <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
     </tr>
    </thead>

   <tbody>
    <% @users.each do |user| %>
    <tr>
     <td><%= image_tag user.get_profile_image(50,50) %></td>
     <td><%= user.name%></td>
     <td><%= link_to 'Show', user_path(user.id) %></td>
    </tr>
   <% end %>
   </tbody>
  </table>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
   <p id="notice">
    <%= flash[:notice] %>
   </p>
<% end %>
<div class="container">
 <div class="row">
  <div class="col-md-3">
   <%= render 'userinfo', user: @user %>
   <%= render 'books/newbook', newbook: @newbook %>
  </div>
  <div class="col-md-8 offset-md-1">
   <h1>Books</h1>
    <table class="table table-striped">
    <thead>
    <tr>
     <th>Title</th>
     <th>Opinion</th>
    </tr>
    </thead>

    <tbody>
    <% @books.each do |book| %>
    <tr>
     <td>
     <%= link_to user_path(book.user.id) do %>
     <%= image_tag book.user.get_profile_image(100,100) %>
     <% end %>
     </td>
     <td><%= link_to book.title, book_path(book.id) %></td>
     <td><%= book.body%></td>
     <% if book.favorited_by?(current_user) %>
         <td>
           <%= link_to book_favorites_path(book), method: :delete do %>
             <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
           <% end %>
         </td>
        <% else %>
         <td>
           <%= link_to book_favorites_path(book), method: :post do %>
             <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
           <% end %>
         </td>
        <% end %>
     <td>コメント数：<%= book.book_comments.count %></td>
    </tr>
     <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>